name: ambiente_pjenergy
channels:
  - conda-forge
dependencies:
  - python=3.10
  - xarray
  - netcdf4
  - cdsapi
  - pytest
  - dask
  - scipy
  # e outros pacotes
  - pip
  - pip:
    - -e .
    # outros pacotes pip que você usa

