name: ambiente_pjenergy
channels:
  - conda-forge
dependencies:
  - python=3.12

  - xarray
  - netcdf4
  - cdsapi
  - dask
  - scipy
  # e outros pacotes
  - pip
  - pip:
    - -e .
    - pytest
    - pytest-cov
    # outros pacotes pip que você usa

